### ISSUE TITLE
Cannot authenticate using generated tokens!

### ISSUE THREAD

**Issue by jmrtorres** [sirinibin/yii2-rest#1]
Hi Sirinibin, nice work!

I'm newbie programmer.

I was testing it and detected some issue. It seams to generate "authorizationCodes" and try login with "acessTokens". 

Can you checkit or explain the suposed behaviour?

Thanks.

**Comment by sirinibin** [comment]
Please check the API documentation on developer dashboard

On 12-Jan-2018 10:01 pm, "jmrtorres" <notifications@github.com> wrote:

Hi Sirinibin, nice work!

I'm newbie programmer.

I was testing it and detected some issue. It seams to generate
"authorizationCodes" and try login with "acessTokens".

Can you checkit or explain the suposed behaviour?

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sirinibin/Yii2-RESTful-API-with-OAuth2/issues/1>, or mute
the thread
